import test from "node:test";
import assert from "node:assert/strict";
import {createAccountStore} from "../../prototypes/shared/account-state.js";
const user={id:"alice",approved:true};
const item={id:"h1",quote:"Exact source words",country:"syria",note:"note-1"};
function fixture(rows=[]){const db=new Map(rows.map(r=>[`${r.kind}/${r.id}`,structuredClone(r)]));const writes=[];
  const request=async(path,data)=>{
    if(path==="/api/account")return{configured:true,user};
    if(path==="/api/saved")return{items:[...db.values()].map(r=>structuredClone(r))};
    const [,kind,rawId]=path.match(/^\/api\/saved\/([^/]+)\/(.+)$/),id=decodeURIComponent(rawId),key=`${kind}/${id}`,current=db.get(key);
    if((current?.revision||0)!==data.revision)throw Object.assign(new Error("Conflict"),{status:409,current:structuredClone(current)});
    const row={kind,id,value:structuredClone(data.value),revision:(current?.revision||0)+1};db.set(key,row);writes.push(row);return{revision:row.revision};
  };return{db,writes,request};}
test("initial account read does not upload guest items",async()=>{const f=fixture();const s=createAccountStore(f.request);await s.initialise();assert.deepEqual(s.snapshot(),{highlights:[],pins:[],reviews:[]});assert.equal(f.writes.length,0);});
test("approved saves write each item and another device reads them",async()=>{const f=fixture(),a=createAccountStore(f.request);await a.initialise();a.replace("highlights",[item]);assert.equal(await a.flush(),true);const b=createAccountStore(f.request);await b.initialise();assert.deepEqual(b.values("highlights"),[item]);});
test("deletions remain tombstones and stale devices cannot resurrect them",async()=>{const f=fixture([{kind:"highlights",id:item.id,value:item,revision:1}]);const a=createAccountStore(f.request),b=createAccountStore(f.request);await a.initialise();await b.initialise();a.replace("highlights",[]);await a.flush();b.replace("highlights",[{...item,comment:"stale change"}]);assert.equal(await b.flush(),false);assert.equal(f.db.get("highlights/h1").value,null);assert.equal(b.state.conflicts.length,1);});
test("conflicts preserve local edits until explicit remote choice",async()=>{const f=fixture([{kind:"highlights",id:item.id,value:item,revision:1}]);const a=createAccountStore(f.request),b=createAccountStore(f.request);await a.initialise();await b.initialise();a.replace("highlights",[{...item,comment:"A"}]);await a.flush();b.replace("highlights",[{...item,comment:"B"}]);await b.flush();assert.equal(b.values("highlights")[0].comment,"B");b.resolve("highlights/h1",false);await b.flush();assert.equal(b.values("highlights")[0].comment,"A");});
test("explicit local conflict resolution uses latest server revision",async()=>{const f=fixture([{kind:"highlights",id:item.id,value:item,revision:1}]);const a=createAccountStore(f.request),b=createAccountStore(f.request);await a.initialise();await b.initialise();a.replace("highlights",[{...item,comment:"A"}]);await a.flush();b.replace("highlights",[{...item,comment:"B"}]);await b.flush();b.resolve("highlights/h1",true);await b.flush();assert.equal(f.db.get("highlights/h1").value.comment,"B");assert.equal(f.db.get("highlights/h1").revision,3);});
test("pending users cannot write account items",async()=>{const s=createAccountStore(async()=>({configured:true,user:{...user,approved:false}}));await s.initialise();assert.throws(()=>s.replace("highlights",[item]),/Approved/);});
test("network failures retain changes and retry confirms them",async()=>{const f=fixture();let offline=true;const s=createAccountStore(async(path,data)=>{if(data&&offline)throw new Error("Offline");return f.request(path,data);});await s.initialise();s.replace("highlights",[item]);assert.equal(await s.flush(),false);assert.equal(s.hasPending(),true);offline=false;assert.equal(await s.flush(),true);assert.equal(s.hasPending(),false);});
test("an edit while saving is sent after the in-flight revision",async()=>{const f=fixture();let release;let blocked=true;const s=createAccountStore(async(path,data)=>{if(data&&blocked){blocked=false;await new Promise(r=>release=r);}return f.request(path,data);});await s.initialise();s.replace("highlights",[item]);s.replace("highlights",[{...item,comment:"updated while saving"}]);release();await s.flush();assert.equal(f.db.get("highlights/h1").value.comment,"updated while saving");assert.equal(s.hasPending(),false);});
test("failed initial read cannot appear saved, accept writes or export a loaded snapshot",async()=>{const f=fixture([{kind:'highlights',id:item.id,value:item,revision:1}]);let unavailable=true;const s=createAccountStore(async(path,data)=>{if(path==='/api/saved'&&unavailable)throw new Error('Unavailable');return f.request(path,data);});await s.initialise();assert.equal(s.state.loaded,false);assert.equal(s.state.status,'unavailable');assert.throws(()=>s.replace('highlights',[item]),/not loaded/);assert.equal(await s.flush(),false);assert.equal(s.state.status,'unavailable');assert.equal(f.writes.length,0);unavailable=false;await s.refresh();assert.equal(s.state.loaded,true);assert.deepEqual(s.values('highlights'),[item]);});
