// Copies third-party code, map data and fonts into prototypes/vendor/ so pages never load from a CDN.
// Run: cd web && npm install && npm run vendor
import { build } from "esbuild";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { inflateSync } from "node:zlib";
import { join } from "node:path";

const require = createRequire(import.meta.url);
const out = new URL("../prototypes/vendor/", import.meta.url).pathname;
mkdirSync(join(out, "fonts"), { recursive: true });

// Keep COBE's complete notice in every distributed library/derived-map copy.
const cobeLicence = readFileSync(new URL("./node_modules/cobe/LICENSE", import.meta.url), "utf8");
const cobeNotice = `/*! COBE by Shu Ding: https://github.com/shuding/cobe\n${cobeLicence.trim()}\n*/`;
mkdirSync(join(out, "licenses"), { recursive: true });
writeFileSync(join(out, "licenses", "COBE-LICENSE.txt"), cobeLicence);

// 1. One ES module with everything the globe needs.
await build({
  stdin: {
    contents: `
      export { default as createGlobe } from "cobe";
      export { geoBounds, geoContains, geoDistance, geoInterpolate } from "d3-geo";
      export { feature, merge } from "topojson-client";
    `,
    resolveDir: new URL(".", import.meta.url).pathname,
    loader: "js",
  },
  bundle: true,
  format: "esm",
  minify: true,
  outfile: join(out, "globe-deps.js"),
  legalComments: "inline",
  banner: { js: cobeNotice },
});

// 1b. One change to COBE's globe shader: land dots that stay sharp when the globe is zoomed.
//     COBE draws each dot as a soft blob (smoothstep from its edge to its centre), which is right at
//     scale 1 and a blur at scale 3. Here the soft band narrows as the scale (uniform x) grows, around
//     the same half-way radius: identical at scale 1, crisp when zoomed in. Fails loudly if COBE's
//     shader ever changes, rather than silently dropping the change.
const PATCHES = [{
  name: "cobe: land dots stay sharp when zoomed",
  find: "smoothstep(8e-3,0.,g)",
  replace: "(1.-smoothstep(4e-3-4e-3*pow(x,-1.6),4e-3+4e-3*pow(x,-1.6),g))",
}, {
  // COBE keeps a style sheet of its own (which of its markers with ids are in view: we have none) and
  // writes it out again on every update(), the same text each time. A rewritten sheet makes the browser go
  // over the page's styles afresh, every frame the globe turns: so it is written only when it has changed.
  name: "cobe: its style sheet is rewritten only when it changes",
  find: 'a.textContent=":root{"+s+"}"',
  replace: '(s=":root{"+s+"}",a.__said!==s&&(a.textContent=a.__said=s))',
}];
{
  const file = join(out, "globe-deps.js");
  let code = readFileSync(file, "utf8");
  for (const { name, find, replace } of PATCHES) {
    if (code.split(find).length !== 2) throw new Error(`vendor patch "${name}" does not apply: expected exactly one "${find}"`);
    code = code.replace(find, replace);
  }
  writeFileSync(file, code);
}

// 1c. The header mark is a miniature of the globe (prototypes/shared/mini-globe.js): it needs COBE's own
//     land map (a 256 x 128 one-bit picture inside COBE) and where each country's dot sits, without
//     loading COBE or the full data. Both go in one small module.
{
  const cobe = readFileSync(require.resolve("cobe"), "utf8");
  const uri = cobe.match(/data:image\/png;base64,([A-Za-z0-9+/=]+)/);
  if (!uri) throw new Error("COBE's land map was not found in its source");
  const map = decodeOneBitPng(Buffer.from(uri[1], "base64"));
  const countryConfig = JSON.parse(readFileSync(new URL("../config/countries.json", import.meta.url), "utf8"));
  const markers = {
    ...countryConfig.historical_markers?.countries,
    ...Object.fromEntries(Object.entries(countryConfig.countries).map(([slug, c]) => [slug, c.marker])),
  };
  writeFileSync(join(out, "globe-mini-data.js"), `${cobeNotice}\n// Generated by web/build-vendor.mjs (npm run vendor). Do not edit.
// LAND: COBE ${JSON.parse(readFileSync(join(new URL("./node_modules/", import.meta.url).pathname, "cobe", "package.json"), "utf8")).version}'s land map, one bit a cell, rows from the north, columns from 180° west (MIT, cobe).
// MARKERS: where each country's dot sits on the globe, [latitude, longitude] (config/countries.json).
export const LAND = { cols: ${map.width}, rows: ${map.height}, bits: "${Buffer.from(map.bits).toString("base64")}" };
export const MARKERS = ${JSON.stringify(markers)};
`);
}
/** A one-bit greyscale or two-colour palette PNG -> { width, height, bits } (packed rows, 1 = light). */
function decodeOneBitPng(png) {
  let at = 8, width = 0, height = 0, type = -1, palette = null;
  const idat = [];
  while (at < png.length) {
    const size = png.readUInt32BE(at), kind = png.toString("latin1", at + 4, at + 8), body = png.subarray(at + 8, at + 8 + size);
    if (kind === "IHDR") {
      width = body.readUInt32BE(0); height = body.readUInt32BE(4); type = body[9];
      if (body[8] !== 1 || (type !== 0 && type !== 3) || body[12] !== 0) throw new Error("COBE's land map is no longer a one-bit, non-interlaced PNG");
    } else if (kind === "PLTE") palette = body;
    else if (kind === "IDAT") idat.push(body);
    at += 12 + size;
  }
  const stride = Math.ceil(width / 8), raw = inflateSync(Buffer.concat(idat)), bits = new Uint8Array(stride * height);
  const lightIsOne = type === 0 || palette[3] > palette[0];                     // palette entry 1 lighter than entry 0
  for (let y = 0; y < height; y++) {
    const filter = raw[y * (stride + 1)], row = raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1));
    for (let x = 0; x < stride; x++) {                                          // undo the row filter (one byte per "pixel" at this depth)
      const a = x ? bits[y * stride + x - 1] : 0, b = y ? bits[(y - 1) * stride + x] : 0, c = x && y ? bits[(y - 1) * stride + x - 1] : 0;
      const p = a + b - c, pa = Math.abs(p - a), pb = Math.abs(p - b), pc = Math.abs(p - c);
      const predicted = filter === 0 ? 0 : filter === 1 ? a : filter === 2 ? b : filter === 3 ? (a + b) >> 1 : pa <= pb && pa <= pc ? a : pb <= pc ? b : c;
      bits[y * stride + x] = (row[x] + predicted) & 255;
    }
  }
  if (!lightIsOne) for (let i = 0; i < bits.length; i++) bits[i] ^= 255;
  return { width, height, bits };
}

// 2. Country borders are built separately by build-borders.mjs (Natural Earth, UK point of view).

// 3. Fonts (Geist family, SIL Open Font License). Read by path: geist's exports map hides package.json.
const modules = new URL("./node_modules/", import.meta.url).pathname;
const geist = join(modules, "geist");
const fonts = {
  "Geist-Variable.woff2": "dist/fonts/geist-sans/Geist-Variable.woff2",
  "GeistMono-Variable.woff2": "dist/fonts/geist-mono/GeistMono-Variable.woff2",
  "GeistPixel-Square.woff2": "dist/fonts/geist-pixel/GeistPixel-Square.woff2",
  "GeistPixel-Line.woff2": "dist/fonts/geist-pixel/GeistPixel-Line.woff2",
};
for (const [name, path] of Object.entries(fonts)) copyFileSync(join(geist, path), join(out, "fonts", name));
copyFileSync(join(geist, "LICENSE.txt"), join(out, "fonts", "GEIST-LICENSE.txt"));

// 4. Flags for the countries with notes (flag-icons, MIT), drawn as dot matrices by dot-flag.js.
//    One JSON file of SVG sources rather than 47 requests.
mkdirSync(join(out, "flags"), { recursive: true });
const countries = JSON.parse(readFileSync(new URL("../config/countries.json", import.meta.url), "utf8")).countries;
const flags = Object.fromEntries(Object.values(countries).map(({ iso_a2 }) =>
  [iso_a2, readFileSync(join(modules, "flag-icons", "flags", "4x3", `${iso_a2}.svg`), "utf8")]));
writeFileSync(join(out, "flags", "flags.json"), JSON.stringify(flags));
copyFileSync(join(modules, "flag-icons", "LICENSE"), join(out, "flags", "FLAG-ICONS-LICENSE.txt"));

const versions = Object.fromEntries(
  ["cobe", "d3-geo", "topojson-client", "geist", "flag-icons"].map((p) => [
    p, JSON.parse(readFileSync(join(modules, p, "package.json"), "utf8")).version,
  ]),
);
const recorded = existsSync(join(out, "VERSIONS.json")) ? JSON.parse(readFileSync(join(out, "VERSIONS.json"), "utf8")) : {};   // build-borders.mjs records the map data here too
writeFileSync(join(out, "VERSIONS.json"), JSON.stringify({ ...recorded, ...versions, patches: PATCHES.map((p) => p.name) }, null, 2) + "\n");
console.log("vendored into", out, versions);
